// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: proto/users/users.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Users_UsersAdd_FullMethodName    = "/users.Users/UsersAdd"
	Users_UsersLogin_FullMethodName  = "/users.Users/UsersLogin"
	Users_UsersInfo_FullMethodName   = "/users.Users/UsersInfo"
	Users_UsersList_FullMethodName   = "/users.Users/UsersList"
	Users_UsersUpdate_FullMethodName = "/users.Users/UsersUpdate"
	Users_UsersDelete_FullMethodName = "/users.Users/UsersDelete"
)

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersClient interface {
	UsersAdd(ctx context.Context, in *UsersAddReq, opts ...grpc.CallOption) (*UsersAddResp, error)
	UsersLogin(ctx context.Context, in *UsersLoginReq, opts ...grpc.CallOption) (*UsersLoginResp, error)
	UsersInfo(ctx context.Context, in *UsersInfoReq, opts ...grpc.CallOption) (*UsersInfoResp, error)
	UsersList(ctx context.Context, in *UsersListReq, opts ...grpc.CallOption) (*UsersListResp, error)
	UsersUpdate(ctx context.Context, in *UsersUpdateReq, opts ...grpc.CallOption) (*UsersUpdateResp, error)
	UsersDelete(ctx context.Context, in *UsersDeleteReq, opts ...grpc.CallOption) (*UsersDeleteResp, error)
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) UsersAdd(ctx context.Context, in *UsersAddReq, opts ...grpc.CallOption) (*UsersAddResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersAddResp)
	err := c.cc.Invoke(ctx, Users_UsersAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UsersLogin(ctx context.Context, in *UsersLoginReq, opts ...grpc.CallOption) (*UsersLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersLoginResp)
	err := c.cc.Invoke(ctx, Users_UsersLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UsersInfo(ctx context.Context, in *UsersInfoReq, opts ...grpc.CallOption) (*UsersInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersInfoResp)
	err := c.cc.Invoke(ctx, Users_UsersInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UsersList(ctx context.Context, in *UsersListReq, opts ...grpc.CallOption) (*UsersListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersListResp)
	err := c.cc.Invoke(ctx, Users_UsersList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UsersUpdate(ctx context.Context, in *UsersUpdateReq, opts ...grpc.CallOption) (*UsersUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersUpdateResp)
	err := c.cc.Invoke(ctx, Users_UsersUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UsersDelete(ctx context.Context, in *UsersDeleteReq, opts ...grpc.CallOption) (*UsersDeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersDeleteResp)
	err := c.cc.Invoke(ctx, Users_UsersDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
// All implementations must embed UnimplementedUsersServer
// for forward compatibility
type UsersServer interface {
	UsersAdd(context.Context, *UsersAddReq) (*UsersAddResp, error)
	UsersLogin(context.Context, *UsersLoginReq) (*UsersLoginResp, error)
	UsersInfo(context.Context, *UsersInfoReq) (*UsersInfoResp, error)
	UsersList(context.Context, *UsersListReq) (*UsersListResp, error)
	UsersUpdate(context.Context, *UsersUpdateReq) (*UsersUpdateResp, error)
	UsersDelete(context.Context, *UsersDeleteReq) (*UsersDeleteResp, error)
	mustEmbedUnimplementedUsersServer()
}

// UnimplementedUsersServer must be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (UnimplementedUsersServer) UsersAdd(context.Context, *UsersAddReq) (*UsersAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersAdd not implemented")
}
func (UnimplementedUsersServer) UsersLogin(context.Context, *UsersLoginReq) (*UsersLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersLogin not implemented")
}
func (UnimplementedUsersServer) UsersInfo(context.Context, *UsersInfoReq) (*UsersInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersInfo not implemented")
}
func (UnimplementedUsersServer) UsersList(context.Context, *UsersListReq) (*UsersListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersList not implemented")
}
func (UnimplementedUsersServer) UsersUpdate(context.Context, *UsersUpdateReq) (*UsersUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersUpdate not implemented")
}
func (UnimplementedUsersServer) UsersDelete(context.Context, *UsersDeleteReq) (*UsersDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersDelete not implemented")
}
func (UnimplementedUsersServer) mustEmbedUnimplementedUsersServer() {}

// UnsafeUsersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServer will
// result in compilation errors.
type UnsafeUsersServer interface {
	mustEmbedUnimplementedUsersServer()
}

func RegisterUsersServer(s grpc.ServiceRegistrar, srv UsersServer) {
	s.RegisterService(&Users_ServiceDesc, srv)
}

func _Users_UsersAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UsersAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UsersAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UsersAdd(ctx, req.(*UsersAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UsersLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UsersLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UsersLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UsersLogin(ctx, req.(*UsersLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UsersInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UsersInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UsersInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UsersInfo(ctx, req.(*UsersInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UsersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UsersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UsersList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UsersList(ctx, req.(*UsersListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UsersUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UsersUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UsersUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UsersUpdate(ctx, req.(*UsersUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UsersDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UsersDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UsersDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UsersDelete(ctx, req.(*UsersDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Users_ServiceDesc is the grpc.ServiceDesc for Users service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Users_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UsersAdd",
			Handler:    _Users_UsersAdd_Handler,
		},
		{
			MethodName: "UsersLogin",
			Handler:    _Users_UsersLogin_Handler,
		},
		{
			MethodName: "UsersInfo",
			Handler:    _Users_UsersInfo_Handler,
		},
		{
			MethodName: "UsersList",
			Handler:    _Users_UsersList_Handler,
		},
		{
			MethodName: "UsersUpdate",
			Handler:    _Users_UsersUpdate_Handler,
		},
		{
			MethodName: "UsersDelete",
			Handler:    _Users_UsersDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/users/users.proto",
}
